### ISSUE TITLE
Licence Issue ?

### ISSUE THREAD

**Issue by vpicavet** [blairscriven/CERC_HAND_D#1]
Hello,

From the LICENCE file, this plugin is intended to be published as GPL. While I really appreciate the intention, I doubt that this can be compatible with being an arcmap plugin. Due to the "viral" aspect of GPL, any link ( like a Python `import` ) would lead to an obligation of compatibility between licences, hence arcmap being distributed as GPL or another compatible licence. I doubt this will happen any day soon.

I would advise to re-licence your plugin as BSD or MIT if you can.

**Comment by blairscriven** [comment]
Thanks for the heads up! 

I am a novice when it comes to licencing software, so thank you for the suggestion

**Comment by vpicavet** [comment]
Great reactivity. On a not-that-related note, we would love to see this plugin ported to QGIS... as GPL :-)

**Comment by blairscriven** [comment]
I would certainly consider that; the wider accessibility of the QGIS platform is certainly appealing.
